language: ruby
cache: bundler
env:
  RAILS_ENV=test
  SECRET_KEY_BASE="$(bundle exec rake secret)"
rvm:
  - "2.0.0"
before_script:
  - bundle exec rake db:create --trace
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle exec rails_best_practices .
  - bundle exec rake rubocop
