#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ubuntu'
cookbook 'apt'
cookbook 'postfix'
cookbook 'build-essential'
cookbook 'git'
cookbook 'postgresql'
cookbook 'memcached'
cookbook 'imagemagick'
