development:
  adapter: postgresql
  encoding: utf8
  database: cloudspace_rss_development
  pool: 100
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: cloudspace_rss_testing
  pool: 100
  username: postgres
  password: postgres
  host: localhost

staging:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['STAGING_POSTGRES_DATABASE'] %>
  pool: 100
  username: <%= ENV['STAGING_POSTGRES_USERNAME'] %>
  password: <%= ENV['STAGING_POSTGRES_PASSWORD'] %>
  host: <%= ENV['STAGING_POSTGRES_HOST'] %>
  port: <%= ENV['STAGING_POSTGRES_PORT'] %>

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['PRODUCTION_POSTGRES_DATABASE'] %>
  pool: 100
  username: <%= ENV['PRODUCTION_POSTGRES_USERNAME'] %>
  password: <%= ENV['PRODUCTION_POSTGRES_PASSWORD'] %>
  host: <%= ENV['PRODUCTION_POSTGRES_HOST'] %>
  port: <%= ENV['PRODUCTION_POSTGRES_PORT'] %>

microservice:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['MICROSERVICE_POSTGRES_DATABASE'] %>
  pool: 100
  username: <%= ENV['MICROSERVICE_POSTGRES_USERNAME'] %>
  password: <%= ENV['MICROSERVICE_POSTGRES_PASSWORD'] %>
  host: <%= ENV['MICROSERVICE_POSTGRES_HOST'] %>
  port: <%= ENV['MICROSERVICE_POSTGRES_PORT'] %>
