Documentation:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

LineLength:
  Max: 120
  Exclude: 
    - 'config/routes.rb'

ClassLength:
  Enabled: true
  CountComments: false
  Max: 150

MethodLength:
  Enabled: false

WhileUntilModifier:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

CyclomaticComplexity:
  Severity: warning
