Documentation:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

LineLength:
  Max: 120
  Exclude: 
    - 'config/routes.rb'
    - 'config/deploy/*'
    - 'app/models/feed_item.rb'

ClassLength:
  Enabled: true
  CountComments: false
  Max: 160

MethodLength:
  Enabled: false

WhileUntilModifier:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

CyclomaticComplexity:
  Severity: warning
