feeds = [{ url: 'http://consequenceofsound.net/feed/', default: true },
         { url: 'http://iwatchstuff.com/index.xml', default: true },
         { url: 'http://otisthecorgi.com/rss', default: true },
         { url: 'http://www.pcworld.com/index.rss' },
         { url: 'http://www.npr.org/rss/rss.php?id=13' },
         { url: 'http://rss.slashdot.org/Slashdot/slashdotBookReviews' },
         { url: 'http://coreos.com/atom.xml' },
         { url: 'http://reviews.cnet.com/4924-3127_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://www.npr.org/rss/rss.php?id=1025' },
         { url: 'http://feeds.feedburner.com/pinchmysalt' },
         { url: 'http://www.npr.org/rss/rss.php?id=1016' },
         { url: 'http://feeds.feedburner.com/thesuperficial/SNxk', default: true },
         { url: 'http://www.infoworld.com/news/feed' },
         { url: 'http://feeds.feedburner.com/geekologie/iShm', default: true },
         { url: 'http://altonbrown.com/feed/' },
         { url: 'http://feeds.bbci.co.uk/news/health/rss.xml?edition=int' },
         { url: 'http://www.npr.org/rss/rss.php?id=1019' },
         { url: 'http://www.washingtonpost.com/wp-dyn/rss/realestate/own/index.xml' },
         { url: 'http://rss.cnn.com/rss/cnn_crime.rss' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', default: true },
         { url: 'http://online.wsj.com/xml/rss/3_7071.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Weddings.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1048' },
         { url: 'http://www.reddit.com/r/itookapicture/.rss' },
         { url: 'http://feeds.mashable.com/Mashable', default: true },
         { url: 'http://reviews.cnet.com/4924-6501_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://feeds.washingtonpost.com/rss/politics' },
         { url: 'http://online.wsj.com/xml/rss/3_7014.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1015' },
         { url: 'http://www.npr.org/rss/rss.php?id=1047' },
         { url: 'http://www.npr.org/rss/rss.php?id=1010' },
         { url: 'http://news.nationalgeographic.com/index.rss' },
         { url: 'http://feeds.bbci.co.uk/news/technology/rss.xml?edition=int' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Music.xml' },
         { url: 'http://www.theguardian.com/books/rss' },
         { url: 'http://doctorcatmd.com/feed' },
         { url: 'http://esquire.feedsportal.com/c/34826/f/641768/index.rss', default: true },
         { url: 'http://feeds.washingtonpost.com/rss/business' },
         { url: 'http://rss.allrecipes.com/2/3.xml' },
         { url: 'http://online.wsj.com/xml/rss/3_7020.xml' },
         { url: 'http://rss.slashdot.org/Slashdot/slashdotit' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/MiddleEast.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1014' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Africa.xml' },
         { url: 'http://www.sciencemag.org/rss/current.xml' },
         { url: 'http://rss.allrecipes.com/2/6.xml' },
         { url: 'http://feeds.huffingtonpost.com/FeaturedPosts' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/ProFootball.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1009' },
         { url: 'http://feeds.bbci.co.uk/news/world/asia/rss.xml?edition=int' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/YourMoney.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1039' },
         { url: 'http://www.usmagazine.com/celebrity_news/rss' },
         { url: 'http://www.npr.org/rss/rss.php?id=1045' },
         { url: 'http://www.nationalgeographic.com/adventure/nga.xml' },
         { url: 'http://i.rottentomatoes.com/syndication/rss/top_dvds.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Sports.xml' },
         { url: 'http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml?edition=int' },
         { url: 'http://www.npr.org/rss/rss.php?id=1018' },
         { url: 'http://www.sciencemag.org/rss/twis.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1003' },
         { url: 'http://www.theverge.com/rss/index.xml', default: true },
         { url: 'http://www.npr.org/rss/rss.php?id=1022' },
         { url: 'http://www.npr.org/rss/rss.php?id=1043' },
         { url: 'http://www.theguardian.com/uk/rss' },
         { url: 'http://rss.cnn.com/rss/cnn_world.rss' },
         { url: 'http://www.engadget.com/rss.xml', default: true },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Golf.xml' },
         { url: 'http://rss.slashdot.org/Slashdot/slashdotApple' },
         { url: 'http://www.crawlingroad.com/blog/feed/' },
         { url: 'http://www.npr.org/rss/rss.php?id=1013' },
         { url: 'http://reviews.cnet.com/4924-3132_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://www.npr.org/rss/rss.php?id=3' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Environment.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/AsiaPacific.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Health.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/ProBasketball.xml' },
         { url: 'http://rss.slashdot.org/Slashdot/slashdotGames' },
         { url: 'http://www.mattcutts.com/blog/feed/' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Nutrition.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Television.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Space.xml' },
         { url: 'http://www.washingtonpost.com/wp-dyn/rss/realestate/dcarealiving/index.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Politics.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1044' },
         { url: 'http://www.rollingstone.com/siteServices/rss/albumReviews' },
         { url: 'http://reviews.cnet.com/4924-6450_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Magazine.xml' },
         { url: 'http://earthobservatory.nasa.gov/Feeds/rss/eo.rss' },
         { url: 'http://feeds.washingtonpost.com/rss/homepage' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Books.xml' },
         { url: 'http://feeds.arstechnica.com/arstechnica/index/' },
         { url: 'http://feeds.feedburner.com/time/pictured' },
         { url: 'http://online.wsj.com/xml/rss/3_7031.xml' },
         { url: 'http://reviews.cnet.com/4924-6462_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://www.rollingstone.com/siteServices/rss/allVideos' },
         { url: 'http://feeds.feedburner.com/456bereastreet' },
         { url: 'http://rss.slashdot.org/Slashdot/slashdotHardware' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Theater.xml' },
         { url: 'http://feeds.huffingtonpost.com/huffingtonpost/LatestNews' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Baseball.xml' },
         { url: 'http://reviews.cnet.com/4924-6500_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Style.xml' },
         { url: 'http://feeds.bbci.co.uk/news/rss.xml?edition=int' },
         { url: 'http://feeds.gawker.com/lifehacker/full' },
         { url: 'http://feeds.bbci.co.uk/news/world/middle_east/rss.xml?edition=int' },
         { url: 'http://www.networkworld.com/netflash.rss' },
         { url: 'http://feeds.boston.com/boston/bigpicture/index', default: true },
         { url: 'http://www.npr.org/rss/rss.php?id=2' },
         { url: 'http://www.npr.org/rss/rss.php?id=1026' },
         { url: 'http://www.npr.org/rss/rss.php?id=1014' },
         { url: 'http://www.npr.org/rss/rss.php?id=1006' },
         { url: 'http://rss.slashdot.org/Slashdot/slashdotpolitics' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Hockey.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=4578972' },
         { url: 'http://feeds.wired.com/wired/index' },
         { url: 'http://feeds.bbci.co.uk/news/uk/rss.xml?edition=int' },
         { url: 'http://online.wsj.com/xml/rss/3_7041.xml' },
         { url: 'http://online.wsj.com/xml/rss/3_7015.xml' },
         { url: 'http://i.rottentomatoes.com/syndication/rss/movie_certified_fresh.xml' },
         { url: 'http://www.theguardian.com/film/rss' },
         { url: 'http://feeds.nationalgeographic.com/ng/NGM/NGM_Magazine' },
         { url: 'http://reviews.cnet.com/4924-3504_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://xkcd.com/rss.xml',
           default: true,
           parser_options: {
             feed_item: {
               image_url: {
                 strategies: [{ name: :xpath, args: ["//div[@id='comic']//img", 'src'] }],
                 min_size: 0
               }
             }
           }
         },
         { url: 'http://i.rottentomatoes.com/syndication/rss/top_movies.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1024' },
         { url: 'http://www.webmasterworld.com/index.rss' },
         { url: 'http://i.rottentomatoes.com/syndication/rss/top_news.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=4724307' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Science.xml' },
         { url: 'http://interglacial.com/rss/new_yorker_cartoon.rss' },
         { url: 'http://www.npr.org/rss/rss.php?id=10' },
         { url: 'http://rss.cnn.com/rss/cnn_allpolitics.rss' },
         { url: 'http://rss.allrecipes.com/2/7.xml' },
         { url: 'http://rss.cnn.com/rss/cnn_topstories.rss' },
         { url: 'http://feeds.feedburner.com/people/photos' },
         { url: 'http://www.npr.org/rss/rss.php?id=1053' },
         { url: 'http://goarticles.com/feeds/category/Home_Gardening/69/recent.rss' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/RealEstate.xml' },
         { url: 'http://news.sciencemag.org/rss/current.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1020' },
         { url: 'http://www.npr.org/rss/rss.php?id=1055' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Travel.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/HealthCarePolicy.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/InternationalBusiness.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Sports.xml' },
         { url: 'http://rss.slashdot.org/Slashdot/slashdotDevelopers' },
         { url: 'http://online.wsj.com/xml/rss/3_7011.xml' },
         { url: 'http://www.sciencemag.org/rss/news.xml' },
         { url: 'http://www.theguardian.com/education/rss' },
         { url: 'http://www.npr.org/rss/rss.php?id=1027' },
         { url: 'http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml?edition=int', default: true },
         { url: 'http://feeds.huffingtonpost.com/huffingtonpost/raw_feed' },
         { url: 'http://i.rottentomatoes.com/syndication/rss/new_releases.xml' },
         { url: 'http://www.atomic-robo.com/feed/' },
         { url: 'http://www.theguardian.com/technology/rss' },
         { url: 'http://www.npr.org/rss/rss.php?id=1041' },
         { url: 'http://www.npr.org/rss/rss.php?id=1008' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/MediaandAdvertising.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1042' },
         { url: 'http://www.rollingstone.com/siteServices/rss/musicNewsAndFeature' },
         { url: 'http://www.thewirelessreport.com/rss.xml' },
         { url: 'http://cloudspace.com/blog/feed.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Business.xml' },
         { url: 'http://goarticles.com/feeds/category/Travel/58/recent.rss' },
         { url: 'http://www.npr.org/rss/rss.php?id=7' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/CollegeFootball.xml' },
         { url: 'http://rss.slashdot.org/Slashdot/slashdotlinux' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Americas.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1040' },
         { url: 'http://reviews.cnet.com/4924-3121_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Soccer.xml' },
         { url: 'http://online.wsj.com/xml/rss/3_7013.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1032' },
         { url: 'http://i.rottentomatoes.com/syndication/rss/in_theaters.xml' },
         { url: 'http://www.theguardian.com/uk/rss' },
         { url: 'http://www.npr.org/rss/rss.php?id=1007' },
         { url: 'http://feeds.bbci.co.uk/news/world/asia/rss.xml?edition=int' },
         { url: 'http://feeds.bbci.co.uk/news/business/rss.xml?edition=int' },
         { url: 'http://rss.cnn.com/rss/money_latest.rss' },
         { url: 'http://reviews.cnet.com/4924-6463_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://rss.feedsportal.com/c/270/f/470440/index.rss' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Automobiles.xml' },
         { url: 'http://www.theguardian.com/sport/rss' },
         { url: 'http://www.nytimes.com/services/xml/rss/nyt/International.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1004' },
         { url: 'http://rss.slashdot.org/Slashdot/slashdot' },
         { url: 'http://rss.cnn.com/rss/cnn_us.rss' },
         { url: 'http://reviews.cnet.com/4924-3000_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/CollegeBasketball.xml' },
         { url: 'http://feeds.bbci.co.uk/news/world/europe/rss.xml?edition=int' },
         { url: 'http://feeds.bbci.co.uk/news/world/africa/rss.xml?edition=int' },
         { url: 'http://rss.slashdot.org/Slashdot/slashdotInterviews' },
         { url: 'http://rss.slashdot.org/Slashdot/slashdotscience' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Technology.xml' },
         { url: 'http://www.rollingstone.com/siteServices/rss/movieReviews' },
         { url: 'http://reviews.cnet.com/4924-3243_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://feeds.feedburner.com/alistapart/main' },
         { url: 'http://feeds.washingtonpost.com/rss/world' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/HomeandGarden.xml' },
         { url: 'http://online.wsj.com/xml/rss/3_7012.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1033' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Europe.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1049' },
         { url: 'http://www.theguardian.com/uk/rss' },
         { url: 'http://rss.allrecipes.com/2/1.xml' },
         { url: 'http://www.rollingstone.com/siteServices/rss/movieReviews' },
         { url: 'http://coloringforgrownups.com/rss' },
         { url: 'http://feeds.feedburner.com/time/photoessays' },
         { url: 'http://www.nasa.gov/rss/dyn/breaking_news.rss' },
         { url: 'http://www.npr.org/rss/rss.php?id=1070' },
         { url: 'http://reviews.cnet.com/4924-3513_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://www.npr.org/rss/rss.php?id=1017' },
         { url: 'http://feeds.bbci.co.uk/news/technology/rss.xml?edition=int' },
         { url: 'http://reviews.cnet.com/4924-3118_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10' },
         { url: 'http://www.nasa.gov/rss/dyn/image_of_the_day.rss' },
         { url: 'http://feeds.feedburner.com/time/dailyrx' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/DiningandWine.xml' },
         { url: 'http://www.theguardian.com/science/rss' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Education.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1030' },
         { url: 'http://www.npr.org/rss/rss.php?id=4467349' },
         { url: 'http://cdn.lrb.co.uk/feeds/lrb' },
         { url: 'http://www.theguardian.com/football/rss' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Movies.xml' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/Arts.xml' },
         { url: 'http://www.npr.org/rss/rss.php?id=1046' },
         { url: 'http://www.phdcomics.com/gradfeed.php' },
         { url: 'http://rss.nytimes.com/services/xml/rss/nyt/ArtandDesign.xml' },
         { url: 'http://feeds.bbci.co.uk/news/science_and_environment/rss.xml?edition=int' }
        ]

feeds.each do |feed_attrs|
  feed = Feed.find_or_initialize_by(url: feed_attrs[:url] && URI(feed_attrs[:url]).normalize.to_s)
  feed.update_attributes(feed_attrs.reject { |k, _v| k == :url })
end

AdminUser.create!(email: 'admin@example.com', password: '12345!', password_confirmation: '12345!') if direction == :up

# Default settings
Setting.create_with(value: 2).find_or_create_by(name: 'backoff_min')
Setting.create_with(value: 6).find_or_create_by(name: 'backoff_max')
Setting.create_with(value: 300).find_or_create_by(name: 'max_per_feed')
